spring.application.name=sitter

spring.datasource.url=jdbc:mysql://localhost:3306/users
spring.datasource.username=
spring.datasource.password=

# Github
spring.security.oauth2.client.registration.github.client-id=
spring.security.oauth2.client.registration.github.client-secret=

# Google
spring.security.oauth2.client.registration.google.client-id=
spring.security.oauth2.client.registration.google.client-secret=


logging.level.org.springframework.security=TRACE