name: Build MVN

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          
      - name: Set up environment variables
        run: |
          echo "DEV_DB_URL=${{ secrets.DEV_DB_URL }}" >> $GITHUB_ENV
          echo "DEV_DB_USERNAME=${{ secrets.DEV_DB_USERNAME }}" >> $GITHUB_ENV
          echo "DEV_DB_PASSWORD=${{ secrets.DEV_DB_PASSWORD }}" >> $GITHUB_ENV

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: babysitter-app
          path: '${{ github.workspace }}/target/*.jar'

      - name: Run Tests
        run: mvn test
